### ISSUE TITLE
Graph not updating on cycle repeat 

### ISSUE THREAD

**Issue by Tbear74** [BuyBitcoinWorldwide/stats#1]
Hi there - I went tho this webpage site and pressed refresh (old dates was one day prior) - this graph did not update for the current day even though new data is showing - please check this. https://stats.buybitcoinworldwide.com/cycle-repeat/2021-05-03

**Comment by JTuwiner** [comment]
We're looking at this now. Thanks for reporting.

**Comment by JTuwiner** [comment]
Can you explain more or screenshot the issue? We tested and it seems to work.

**Comment by Tbear74** [comment]
![image](https://user-images.githubusercontent.com/83664186/117360768-77fa3080-aeb9-11eb-9149-45beb3e937d2.png)

**Comment by Tbear74** [comment]
As you can see the ggraph is not updating, I refreshed the page and chose 2021-05-06. The graph shows 2021-05-03. It  must be a cookies things?? but worth noting this has never happened before with the previous site - so the 3 rd was the last day I used this web-page

**Comment by Tbear74** [comment]
I manually changed the date from  https://stats.buybitcoinworldwide.com/cycle-repeat/2021-05-03 to https://stats.buybitcoinworldwide.com/cycle-repeat/2021-05-06 and it now has the most updated graph which is correct. So the pull down menu choosing 2021-05-06 did not refresh to that date for me

**Comment by JTuwiner** [comment]
We see the issue and are working on a fix. Thanks for letting us know!

**Comment by JTuwiner** [comment]
@Tbear74 This is fixed now. can you confirm it's working?

**Comment by Tbear74** [comment]
Yes it is working now! Great Job

**Comment by JTuwiner** [comment]
Thanks! Please let us know about any other issues if you see them.

Also, feel free to request new charts or features.
