### ISSUE TITLE
RHODL Ratio chart

### ISSUE THREAD

**Issue by jwchong** [BuyBitcoinWorldwide/stats#10]
https://www.lookintobitcoin.com/charts/rhodl-ratio/

May I suggest to create RHODL Ratio chart?

Thank you.

**Comment by JTuwiner** [comment]
We're looking into it. will update you

**Comment by jwchong** [comment]
Any update?

**Comment by JTuwiner** [comment]
Look for it to go live later today!

**Comment by jwchong** [comment]
I still cannot find it in the website.
