### ISSUE TITLE
Price vs cost of production

### ISSUE THREAD

**Issue by Emoji-Check** [BuyBitcoinWorldwide/stats#13]
Your guys' website is awesome! Do you think you'd benefit from adding a chart which shows the price of btc vs the average cost to mine 1 btc? (like https://en.macromicro.me/charts/29435/bitcoin-production-total-cost)

Notwithstanding the assumptions involved in determining a global avg. electrical cost and mining equipment hash rate, I find it provides an interesting way to 'value' btc and timing signal when avg cost > price for a couple months.

Cheers!

![Untitled](https://user-images.githubusercontent.com/97533651/148963734-4a948a7f-29a7-4699-b404-d641bfb36e20.png)

**Comment by JTuwiner** [comment]
we're looking into this. thanks for the suggest!
