### ISSUE TITLE
Charting the Bitcoin Entity-Adjusted Dormancy Flow

### ISSUE THREAD

**Issue by kpspcu** [BuyBitcoinWorldwide/stats#14]
Dear all,

it would be nice if we as a community could chart the glassnode metric "Bitcoin Entity-Adjusted Dormancy Flow". This on-chain indicator is very rare and can help identify local or cyclical bottom territories which would eventually indicate major buy-in or accumulate zones on a macro-scaled basis. I for myself do not have the technical knowledge but maybe my idea is heard and is implemented by experts who see the need and the benefit of this rare and special indicator. I would appreciate analysing the indicator open source on https://stats.buybitcoinworldwide.com/

This address could be an example for the digital implementation of this indicator. 
https://stats.buybitcoinworldwide.com/EntityAdjustedDormancyFlow

Cryptographic regards. Stay level-headed.
kpscpu

**Comment by JTuwiner** [comment]
please give me an example or the formula background

**Comment by kpspcu** [comment]
![glassnode-studio_bitcoin-entity-adjusted-dormancy-flow](https://user-images.githubusercontent.com/97692972/149526438-3050d9ed-a76e-4bb0-9093-bbd82c539e30.png)

**Comment by kpspcu** [comment]
This is how it looks like on glassnode but one has got to pay for it so it would be nicer if it was open source. The specific zone which is highlighted in green is the most important buy-in zone, thus we should indicate and highlight in our charts too.

**Comment by kpspcu** [comment]
> please give me an example or the formula background

![glassnode-studio_bitcoin-entity-adjusted-dormancy-flow](https://user-images.githubusercontent.com/97692972/149526606-acc81b5a-e00a-4857-810e-5a62d3e6b0bb.png)

**Comment by kpspcu** [comment]
> please give me an example or the formula background

![Uploading 16421685925633937413518886203015.jpg…]()

**Comment by kpspcu** [comment]
> please give me an example or the formula background

https://medium.com/@kenoshaking/bitcoin-average-dormancy-28f88ea4c2ce

This is where you'll get the formula

**Comment by kpspcu** [comment]
> please give me an example or the formula background

![16421689275446038675276719465903](https://user-images.githubusercontent.com/97692972/149527580-62f0d738-d556-4580-bf85-039fb396a8ce.jpg)

This picture show a detailed version of the Dormancy formula. So it should be easy to connect this formula with the general formula which is in glassnode's article namely this one

![image](https://user-images.githubusercontent.com/97692972/149527859-adcf564a-868a-469d-8359-21a8ee6affba.png)

**Comment by JTuwiner** [comment]
You're asking us to make this chart on our site? We will look into it. Any other charts you want? We are open to ideas.
