### ISSUE TITLE
Bitcoin dormant coins is equal to total mined Bitcoins

### ISSUE THREAD

**Issue by KaiWangCanada** [BuyBitcoinWorldwide/stats#15]
At Jan 15, 2022, the total unspent coin in Bitcoin Dormant Coins is 18.93M. That is about the same to the total Bitcoins mined by then. How is that possible? Is there something wrong with the algorithm?
Thanks!
![image](https://user-images.githubusercontent.com/10340634/149637821-358c1320-ad84-4708-9f86-908c5a72e00a.png)

**Comment by JTuwiner** [comment]
look at bottom,it shows total unspent. red line is total number of coins
