### ISSUE TITLE
Followup Issue: https://github.com/BuyBitcoinWorldwide/stats/issues/10

### ISSUE THREAD

**Issue by jwchong** [BuyBitcoinWorldwide/stats#16]
Followup Issue: https://github.com/BuyBitcoinWorldwide/stats/issues/10

You have closed the issue but I cannot find the RHODL Ratio chart in your website.
Can you provide a link if you have that page?

Thank you

**Comment by JTuwiner** [comment]
we had it up but there is a bug. working on getting it back. will update you.

**Comment by jwchong** [comment]
Still having bug? Not yet see the chart. :-)
