### ISSUE TITLE
include derivatives in the Flow factor of S2F model

### ISSUE THREAD

**Issue by oru2day** [BuyBitcoinWorldwide/stats#18]
Hi, thanks for your great job, I’m a fan of the S2F model from PlanB, but I’m asking myself wether the Flow factor should only be the new bitcoin minting… Measuring the production should include all kind of offers that are available on the market for investors who want to have some exposure to bitcoin ?  Scarcity has an impact on demand and therefore on price, but all giant volumes of derivatives (options, futures, CFDs, ETFs…) are available to investors as well as - and on top of - the actual bitcoins. Considering that derivatives volumes are moving but tend to repeat - and maybe grow - with time, it might be correct to include them in both the Stock and the Flow factors ?
I’m not a specialist, no doubt you will give me an insightful light on this issue. Thanks

**Comment by JTuwiner** [comment]
I guess the argument against would be that the coins on these things you mention are already in against so not related to new supply.
