### ISSUE TITLE
Feature request - Before halving bottom for Bitcoin cycle repeat chart

### ISSUE THREAD

**Issue by azhakha** [BuyBitcoinWorldwide/stats#2]
Hi Team, may i request a label for After Halving Bottom for Bitcoin cycle repeat chart? Thank you.

**Comment by JTuwiner** [comment]
Can you explain more please?

**Comment by azhakha** [comment]
I have edited the "after" and "before" in my request.

It is similar to the existing "After halving top" label that the chart has right now, except that it is for the lowest price point before the halving date.

**Comment by JTuwiner** [comment]
Please can you give more info?
