### ISSUE TITLE
please bring back historic BTC 12 month RSI graph 🙏

### ISSUE THREAD

**Issue by ksaitor** [BuyBitcoinWorldwide/stats#22]
Just checked the site today and noticed that graph was removed. Was super useful!

**Comment by JTuwiner** [comment]
This one? https://www.buybitcoinworldwide.com/stats/monthly-rsi/

**Comment by JTuwiner** [comment]
We just moved domain from subdomain to main domain, so sorry if that's causing issues. Let me know which chart and we'll make sure to add it back if it's gone

**Comment by ksaitor** [comment]
> This one? https://www.buybitcoinworldwide.com/stats/monthly-rsi/

yep! this one. Thanks @JTuwiner

**Comment by JTuwiner** [comment]
No problem! If you have any other charts you want us to add we're always open to tips. Glad you're enjoying the site!
