### ISSUE TITLE
Numbers on scale

### ISSUE THREAD

**Issue by 6992323** [BuyBitcoinWorldwide/stats#7]
![F7CEA97E-6AF7-41CC-98A2-1221FAF73891](https://user-images.githubusercontent.com/89049316/129639546-4026968f-890a-45de-9283-5d4f40110f5a.jpeg)
Hi! Scale stopped working on mobile (iphone)

**Comment by JTuwiner** [comment]
looking at this, thanks!

**Comment by JTuwiner** [comment]
fixed
