### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by cryptojoseph** [BuyBitcoinWorldwide/stats#8]
on this page:

https://stats.buybitcoinworldwide.com/mayer-bands/

there is a typo:

Summary of Mayer Multiple
The Mayer Multiple is calculated by taking the price of Bitcoin and dividing it by the 200 day moving average value. The thinking behind the multiple is that by comparing the current price of bitcoin and its longer term moving average, you get a sense of if it is overbought (overvalued) or oversold (**overvalued**).

Should read "...you get a sense if it is overbought (overvalued) or oversold (UNDERvalued)"

Ciao

J

**Comment by JTuwiner** [comment]
fixed. thanks!
