### ISSUE TITLE
Historic price chart

### ISSUE THREAD

**Issue by DevZay** [BuyBitcoinWorldwide/stats#9]
Amazing site!  How about adding just a standard historic price chart?

**Comment by JTuwiner** [comment]
is this good? https://www.buybitcoinworldwide.com/price/ 

Or you want something different?

**Comment by DevZay** [comment]
I'm a pleb for not noticing that!
But I was also thinking of the functionality of the other charts on the site - where you can drag a rectangle on a zone to zoom in?

________________________________

**Comment by JTuwiner** [comment]
What about disabling the S2F and then you only have price left on the chart? https://stats.buybitcoinworldwide.com/stock-to-flow/

**Comment by DevZay** [comment]
Amazing!
Thanks!

________________________________
